
### below end points to make a request for the data model running on port number 3000 

GET http://localhost:3000/products


###
GET http://localhost:3000/users

###

GET http://localhost:3000/cart

### 
http://localhost:3000/usersHistory

### 
http://localhost:3000/promotions

### 
 http://localhost:3000/wishList

### 
 http://localhost:3000/shippingDelivery



### below end points to make request for data at port number 3001


### get all products 

http://localhost:3001/products


### get products by page - gives 10 products
http://localhost:3001/products?_page=1


### get products with avg ratings = 2 
http://localhost:3001/products?ratings.averageRatings=2

### get with number of reviews more than 4 (you can try with lte) 
http://localhost:3001/products?ratings.numberOfReviews_gte=4&_page=1


### sort by title, descending and avg rating= 2 
http://localhost:3001/products?_sort=title&_order=desc&ratings.averageRatings=2



### get by id 
http://localhost:3001/products/3


### exclude food productCategory and paginate to page 1 only 
http://localhost:3001/products?productCategory_ne=food&_page=1





